# Generated by Django 5.2.7 on 2025-10-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='año_mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=5)),
                ('serie_letra', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=10)),
                ('banco', models.CharField(max_length=100)),
            ],
        ),
    ]
